spring.application.name=payment_api
spring.datasource.url=jdbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=W7301@jqir#

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true